A lot of changes in one commit :(

diff --git a/src/assignment1/user-mngt b/src/assignment1/user-mngt
--- a/src/assignment1/user-mngt
+++ b/src/assignment1/user-mngt
@@ -1,5 +1,5 @@
 #!/bin/bash
-#user-mgr
+# user-mngt
 
 # set options
 set -eu
@@ -25,29 +25,30 @@ Usage:
 	CSV-FILE:	Path to an existing csv file including comma separated
 			data: <first-name>,<last-name>,<password>,<add/remove>
 Examples:
-	Manage users without creating passwords for new users:	${script_name} ~/users.csv" 
-	Manage users and add password for new users:		${script_name} -p ~/users.csv"
+	Manage users without creating passwords for new users:	sudo ${script_name} ~/users.csv" 
+	Manage users and add password for new users:		sudo ${script_name} -p ~/users.csv"
 END
 )
 
-function usage() {
+function help() {
 	# output help text to stdout
 	echo "${usage}"
 }
 
-function log() {
-	msg="$1"
+#function log() {
+#	msg="$1"
 
-	# format a message so that it is prepended with a timestamp and redirect to stderr
-	printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S.%3N')" "${msg}" >&2
-}
+# format a message so that it is prepended with a timestamp and redirect to stderr
+#printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S.%3N')" "${msg}" >&2
+#	echo "${msg}" >&2
+#}
 
 function encrypt_passwd() {
 	local username="$1"
 	local passwd="$2"
 
 	# output 'Generating hash for <username>' to stderr
-	log "Generating hash for ${username}"
+	echo "Generating hash for ${username}" >&2
 	passwd=$(mkpasswd -m SHA-512 "${passwd}")
 	echo \'"${passwd}"\'
 }
@@ -59,20 +60,27 @@ function add() {
 	local username=${fname:0:3}${lname:0:3}
 
 	# build command
-	cmd="useradd --comment \"${fname} ${lname}\""
-	if [ -n "${passwd}" ]; then
-		cmd+=" -p $(encrypt_passwd "${username}" "${passwd}") ${username}"
+	#cmd="useradd --comment \"${fname} ${lname}\""
+	#cmd="adduser --gecos '${fname} ${lname}' "
+	if [ "${passwd}" == null ]; then
+		cmd="adduser --disabled-login --gecos \"${fname} ${lname}\" --home /home/${username} ${username}"
+		# encrypt password
+		#passwd=$(encrypt_passwd "${username}" "${passwd}")
+		#cmd+=" -p ${passwd} ${username}"
 	else
-		cmd+=" \"${username}\" && passwd -e \"${username}\""
+		# set password expired
+		#cmd+=" \"${username}\" && passwd -e \"${username}\""
+		passwd=$(encrypt_passwd "${username}" "${passwd}")
+		cmd="useradd --comment \"${fname} ${lname}\" -p ${passwd} ${username} -m --home /home/${username}"
 	fi
 
 	# execute command
-	if eval "${cmd}" 2>&1; then
+	if eval "${cmd} >/dev/null"; then
 		# success => output "Add <username>" to stdout and logfile
-		log "Add ${username}" 2>&1 | tee -a "${log_file}"
+		echo "Add ${username}" | tee -a "${log_file}"
 	else
 		# error => output error message to stderr
-		log "Error while adding user ${username}: "
+		echo "Error while adding user ${username} " 1>&2
 	fi
 }
 
@@ -81,22 +89,25 @@ function remove() {
 	local lname="$2"
 	local username=${fname:0:3}${lname:0:3}
 
+	#echo "function remove: userdel ${username}"
+
 	# remove user
-	if userdel "${username}"; then
+	if id "${username}" >/dev/null; then
+		userdel -r "${username}"
 		# success => output "Remove <username>" to stdout and logfile
-		log "Remove ${username}" 2>&1 | tee "${log_file}"
+		echo "Remove ${username}" | tee -a "${log_file}"
 	else
 		# error => output error to stderr
-		log "Error while removing user ${username}"
+		echo "Error while removing user ${username}" >&2
 	fi
 }
 
 function update_users() {
 	# redirect <csv_file> to stdin and process/parse the csv data at
-	# each line into variables
+	# each line into variables and call function add/remove
 	while IFS=, read -r fname lname passwd func; do
 		cmd="${func} ${fname} ${lname}"
-		if [[ ${gen_passwd} && "${func}" == "add" ]]; then
+		if [[ ${gen_passwd} == true && "${func}" == "add" ]]; then
 			cmd+=" ${passwd}"
 		fi
 		# execute command
@@ -108,7 +119,7 @@ function update_users() {
 while [ $# -gt 0 ]; do
 	case "$1" in
 	-h | --help)
-		usage
+		help
 		exit 0
 		;;
 	-p | --passwd)
@@ -117,7 +128,7 @@ while [ $# -gt 0 ]; do
 		;;
 	-*)
 		echo "Invalid_option $1"
-		usage
+		help
 		exit 1
 		;;
 	*)
@@ -129,16 +140,17 @@ done
 
 # validate that the sript is called with exactly one parameter
 if [ $# -gt 1 ]; then
-	echo "Script '${script_name}' must be called with exactly one argument!"
+	echo "Script '${script_name}' must be called with exactly one argument"
 	exit 1
 elif [ "$csv_file" = null ]; then
-	echo "Missing required <CSV-FILE> argument!"
+	echo "Missing required <CSV-FILE> argument" >&2
+	help
 	exit 1
 fi
 
 # validate that specified <CSV-FILE> argument is a file
 if [ ! -f "${csv_file}" ]; then
-	echo "Specified path '${csv_file}' is not a file!"
+	echo "Specified path '${csv_file}' is not a file" >&2
 	exit 1
 fi
 
